# Generated by Django 5.2.8 on 2025-12-19 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0004_location"),
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Event name")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("TN", "Tournament"),
                            ("LG", "League"),
                            ("FR", "Friendly"),
                        ],
                        default="LG",
                        max_length=2,
                        verbose_name="Event Type",
                    ),
                ),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="core.location",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "default_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="EventTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PD", "Pending"),
                            ("AP", "Approved"),
                            ("RJ", "Reject"),
                        ],
                        default="AP",
                        max_length=2,
                    ),
                ),
                (
                    "coach",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coached_event_teams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.event"
                    ),
                ),
                (
                    "leader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="led_event_teams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="teams.team"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="teams",
            field=models.ManyToManyField(
                related_name="events", through="events.EventTeam", to="teams.team"
            ),
        ),
        migrations.CreateModel(
            name="EventTeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_player", models.BooleanField(blank=True, default=False)),
                ("is_coach", models.BooleanField(blank=True, default=False)),
                ("is_staff", models.BooleanField(blank=True, default=False)),
                (
                    "event_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster",
                        to="events.eventteam",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="eventteam",
            constraint=models.UniqueConstraint(
                fields=("event", "team"),
                name="unique_event_team",
                violation_error_message="The combination of Event and Team must be unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("start_time__isnull", True),
                    ("end_time__isnull", True),
                    ("start_time__lt", models.F("end_time")),
                    _connector="OR",
                ),
                name="check_start_time_before_end_time",
                violation_error_message="The event end time must be later than the start time.",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventteammember",
            constraint=models.UniqueConstraint(
                fields=("event_team", "user"),
                name="unique_eventteam_user",
                violation_error_message="The combination of EventTeam and User must be unique",
            ),
        ),
    ]
