# Generated by Django 5.2.8 on 2025-12-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventteam",
            name="status",
            field=models.CharField(
                choices=[("PD", "Pending"), ("AP", "Approved"), ("RJ", "Rejected")],
                default="AP",
                max_length=2,
            ),
        ),
    ]
