# Generated by Django 5.2.8 on 2025-12-29 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_lunchoption_registrationlunchorder"),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventteam",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_teams",
                to="events.event",
            ),
        ),
        migrations.AlterField(
            model_name="eventteam",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_teams",
                to="teams.team",
            ),
        ),
    ]
