# Generated by Django 5.2.8 on 2025-12-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_alter_eventteam_event_alter_eventteam_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="lunchoption",
            name="price",
            field=models.PositiveIntegerField(default=80),
        ),
    ]
