# Generated by Django 6.0.1 on 2026-01-23 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_lunchoption_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventteammember',
            name='event_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_team_members', to='events.eventteam'),
        ),
    ]
