# Generated by Django 6.0.1 on 2026-01-26 02:46

import apps.events.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_eventteammember_event_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, verbose_name='Template Name')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matches_matchtemplate',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventMatchConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_config', models.JSONField(blank=True, default=apps.events.models.get_default_rule_config, help_text='Configuration for scoring rules (e.g. winning_sets, etc.)')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_config', to='events.event')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_configs', to='events.matchtemplate')),
            ],
            options={
                'db_table': 'matches_eventmatchconfigureation',
                'ordering': ['created_at'],
            },
        ),
    ]
