# Generated by Django 6.0.1 on 2026-01-28 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_matchtemplate_eventmatchconfiguration'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='eventmatchconfiguration',
            table=None,
        ),
        migrations.AlterModelTable(
            name='matchtemplate',
            table=None,
        ),
    ]
