# Generated by Django 6.0.1 on 2026-01-28 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_is_verified'),
        ('events', '0008_alter_eventmatchconfiguration_table_and_more'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventMatchTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('format', models.CharField(choices=[('S', 'Single'), ('D', 'Double')], default='S', max_length=1, verbose_name='match format')),
                ('requirement', models.CharField(blank=True, default='', help_text='Specify the age, gender, or category for this match (e.g., "30+ Men\'s Singles", "120+ Mixed Doubles").', max_length=32, verbose_name='Match requirement')),
                ('number', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='event',
            name='check_start_time_before_end_time',
        ),
        migrations.RemoveConstraint(
            model_name='eventteam',
            name='unique_event_team',
        ),
        migrations.RemoveConstraint(
            model_name='eventteammember',
            name='unique_eventteam_user',
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__isnull', True), ('end_time__isnull', True), ('start_time__lt', models.F('end_time')), _connector='OR'), name='events_event_check_start_time_before_end_time', violation_error_message='The event end time must be later than the start time.'),
        ),
        migrations.AddConstraint(
            model_name='eventteam',
            constraint=models.UniqueConstraint(fields=('event', 'team'), name='events_eventteam_unique_event_team', violation_error_message='The combination of Event and Team must be unique'),
        ),
        migrations.AddConstraint(
            model_name='eventteammember',
            constraint=models.UniqueConstraint(fields=('event_team', 'user'), name='events_eventteammember_unique_eventteam_user', violation_error_message='The combination of EventTeam and User must be unique'),
        ),
        migrations.RenameModel(
            old_name='MatchTemplate',
            new_name='EventMatchTemplate',
        ),
        migrations.AddField(
            model_name='eventmatchtemplateitem',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='events.eventmatchtemplate'),
        ),
        migrations.AddConstraint(
            model_name='eventmatchtemplateitem',
            constraint=models.UniqueConstraint(fields=('template', 'number'), name='events_eventmatchtemplateitem_unique_template_item_number', violation_error_message='Match number must be unique within a template.'),
        ),
    ]
