# Generated by Django 6.0.1 on 2026-02-04 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_eventmatchtemplateitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmatchconfiguration',
            name='count_points_by_sets',
            field=models.BooleanField(default=False, help_text='Whether to count set scores (e.g. 4:2) or win/loss (1:0)'),
        ),
        migrations.AddField(
            model_name='eventmatchconfiguration',
            name='play_all_matches',
            field=models.BooleanField(default=False, help_text='Must play all matches, overrides team_winning_points setting'),
        ),
        migrations.AddField(
            model_name='eventmatchconfiguration',
            name='play_all_sets',
            field=models.BooleanField(default=False, help_text='Must play all sets, overrides winning_sets setting'),
        ),
        migrations.AddField(
            model_name='eventmatchconfiguration',
            name='set_winning_points',
            field=models.PositiveSmallIntegerField(default=11, help_text='Points needed to win a single set'),
        ),
        migrations.AddField(
            model_name='eventmatchconfiguration',
            name='team_winning_points',
            field=models.PositiveSmallIntegerField(default=3, help_text='Number of points (matches) to win a TeamMatch'),
        ),
        migrations.AddField(
            model_name='eventmatchconfiguration',
            name='use_deuce',
            field=models.BooleanField(default=True, help_text='Whether to use deuce rule (must win by 2 points)'),
        ),
        migrations.AddField(
            model_name='eventmatchconfiguration',
            name='winning_sets',
            field=models.PositiveSmallIntegerField(default=3, help_text='Number of sets to win a PlayerMatch'),
        ),
        migrations.AlterField(
            model_name='eventmatchconfiguration',
            name='rule_config',
            field=models.JSONField(blank=True, default=None, help_text='Configuration for scoring rules (e.g. winning_sets, etc.)'),
        ),
        migrations.AlterField(
            model_name='eventmatchconfiguration',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_configs', to='events.eventmatchtemplate'),
        ),
    ]
