# Generated by Django 6.0.1 on 2026-02-04 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_eventmatchconfiguration_count_points_by_sets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmatchconfiguration',
            name='rule_config',
            field=models.JSONField(blank=True, default=None, help_text='Configuration for scoring rules (e.g. winning_sets, etc.)', null=True),
        ),
    ]
