# Generated by Django 6.0.1 on 2026-02-04 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_eventmatchconfiguration_rule_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmatchconfiguration',
            name='rule_config',
        ),
    ]
