# Generated by Django 6.0.1 on 2026-06-29 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_remove_eventmatchconfiguration_rule_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFavorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_favorites', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='favorites',
            field=models.ManyToManyField(related_name='event_favorites', through='events.EventFavorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='eventfavorites',
            constraint=models.UniqueConstraint(fields=('user', 'event'), name='events_eventfavorites_unique_user_event', violation_error_message='The combination of Event and User must be unique'),
        ),
    ]
