# Generated by Django 6.0.1 on 2026-07-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_eventfavorites_event_favorites_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventteam',
            name='max_member',
            field=models.IntegerField(blank=True, default=8),
        ),
        migrations.AddField(
            model_name='eventteam',
            name='max_waitlist',
            field=models.IntegerField(blank=True, default=4),
        ),
        migrations.AddField(
            model_name='eventteammember',
            name='request_waitlist_only',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='eventteammember',
            name='status',
            field=models.CharField(choices=[('RG', 'REGULAR'), ('WL', 'WAITLIST')], default='RG', max_length=2),
        ),
    ]
