# Generated by Django 6.0.1 on 2026-07-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_eventteam_max_member_eventteam_max_waitlist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='appendix',
            field=models.FileField(blank=True, null=True, upload_to='appendix/%Y/%M'),
        ),
    ]
