# Generated by Django 6.0.1 on 2026-07-16 10:11

import apps.events.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_event_appendix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='appendix',
        ),
        migrations.CreateModel(
            name='EventAttachments',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=apps.events.models.attachment_directory_path)),
                ('original_name', models.CharField(max_length=255)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_attachments', to='events.event')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
