
@startuml
' 隱藏圓點，避免與連結線衝突
hide circle
' 設定線條為正交直線
skinparam linetype ortho



abstract class AbstractUser {
    + username
    + password
    + first_name
    + last_name
    + email
    + is_staff
    + is_active
    + is_superuser
    + last_login
    + date_joined
    + groups : manyToManyField
    + user_permissions : manyToManyField
}

class "User" as User {
    + username : {derived} {None}
    + email : {derived} {unique}
    ' + email : << override, unique=Ture >>
    --
    + full_name : String
    + data_of_birth : Date {optional}
    + avatar : Image {optional}
    + created_at : DataTime
    + updated_at : DateTime
    ' + data_of_birth : << blank=True >>
    ' + avatar : << null=True >> 
}
AbstractUser <|-- User

class "Team" as Team {
    + team_name : String
    + leader_id : <<FK>> {nullable}
    + coach_id : <<FK>> {nullable}
    --
    { unique_together = (team_name, contant_persion_id)}
}

class "TeamMember" as TeamMember {
    + team_id : << FK >>
    + user_id : << FK >>
    --
    { unique_together = ('team_id', 'user_id')}
}

class "Event" as Event {
    + event_name : String
    + location : String
    + start_time : DateTime
    + end_time : DateTime
}

' event_id, teamA_id, teamB_id 不為unique_together
' 避免複賽重複對戰
class "TeamMatch" as TeamMatch {
    + event_id : << FK >>
    + team_a_id : << FK >>
    + team_b_id : << FK >>
    --
    + team_a_score : Int
    + team_b_score : Int
    + match_status : Enum{Scheduled,  Completed}
}

class "PlayerMatch" as PlayerMatch {
    + team_match_id : << FK >>
    + match_order : Int
    + match_format : Enum{Single, Double}
    + team_a_user_a_id : << FK >>
    + team_a_user_b_id : << FK >> {nullable, for double}
    + team_b_user_a_id : << FK >>
    + team_b_user_b_id : << FK >> {nullable, for double}
    --
    + team_a_score : Int
    + team_b_score : Int
    + score_details : JsonField ' [{"a": "11", "b", "3"},
                                '  {"a": "11", "b", "3"},
                                '  {"a": "11", "b", "3"},]
    --
    + { unique_together = ('team_match_id', 'match_order')}
}

class "Roster" as Roster {
    + user_id : << FK >>
    + team_id : << FK >>
    + team_match_id : << FK >>
    --
    + point : Int
    + is_played: Bool
    + notes : String
    --
    {unique_together = (user_id, team_id, team_match_id)}
}

User "1" -- "*" Team

User "1" -- "*" Roster
Team "1" -- "*" Roster
TeamMatch "1" -- "*" Roster

User "1" -- "*" TeamMember
Team "1" -- "*" TeamMember

TeamMatch "1" -- "*" PlayerMatch
User "1" -- "*" PlayerMatch : teamA_userA
User "1" -- "*" PlayerMatch : teamA_userB
User "1" -- "*" PlayerMatch : teamB_userA
User "1" -- "*" PlayerMatch : teamB_userB

Event "1" -- "*" TeamMatch
Team "1" -- "*" TeamMatch : teamA
Team "1" -- "*" TeamMatch : teamB

@enduml