@startuml
' 隱藏圓點，避免與連結線衝突
hide circle
' 設定線條為正交直線
skinparam linetype ortho



abstract class AbstractUser {
    + username
    + password
    + first_name
    + last_name
    + email
    + is_staff
    + is_active
    + is_superuser
    + last_login
    + date_joined
    + groups : manyToManyField
    + user_permissions : manyToManyField
}

class "User" as User {
    + username : {derived} {None}
    + email : {derived} {unique}
    ' + email : << override, unique=Ture >>
    --
    + full_name : String
    + date_of_birth : Date {optional}
    + avatar : Image {optional}
    + created_at : DateTime
    + updated_at : DateTime

    + phone : Str 'Could potentially use the  django-phonenumber-field package
    + is_verified : Bool
}
AbstractUser <|-- User


' ------ 隊伍 ------
class "Team" as Team {
    + team_name : String {nuique=True}
    + leader_id : <<FK>> {nullable}
    + coach_id : <<FK>> {nullable}
    --
}

class "TeamMember" as TeamMember {
    + team_id : << FK >>
    + user_id : << FK >>
    --
    { unique_together = ('team_id', 'user_id')}
}

' ------ 比賽 ------
class "Event" as Event {
    + event_name : String
    + event_type : Enum{tournament, league, friendly}
    + location : String
    + start_time : DateTime
    + end_time : DateTime
    + create_at : DateTime{}
}

' event_id, teamA_id, teamB_id 不為unique_together
' 避免複賽重複對戰
class "TeamMatch" as TeamMatch {
    + event_id : << FK >>
    + team_a_id : << FK >>
    + team_b_id : << FK >>
    --
    + team_a_score : Int
    + team_b_score : Int
    + match_data : DateField
    + match_time : TimeField {nullable}
    + match_status : Enum{Scheduled, InProgress, Completed}

    + create_at : DateTime
    + updated_at : DateTime
}

class "PlayerMatch" as PlayerMatch {
    + team_match_id : << FK >>
    + match_type : Str '競賽型態：單打、雙打、三打？
    + match_order : Int '第幾個排點
    + match_format : Enum{Single, Double}
    + team_a_player : JsonField ' 使用Json格式儲存，支援不限型態的同競賽模式
    + team_b_player : JsonField ' 例如：[1, 4] 代表 user_id=1, user_id=4 的選手上場
    --
    + team_a_score : Int
    + team_b_score : Int
    + score_details : JsonField ' [{"a": "11", "b": "3"},
                                '  {"a": "11", "b": "3"},
                                '  {"a": "11", "b": "3"},]
    --
    + { unique_together = ('team_match_id', 'match_order')}
}


User "1" -- "*" Team : leader
User "1" -- "*" Team : coach


User "1" -- "*" TeamMember
Team "1" -- "*" TeamMember


Event "1" -- "*" TeamMatch
Team "1" -- "*" TeamMatch : teamA
Team "1" -- "*" TeamMatch : teamB


TeamMatch "1" -- "*" PlayerMatch

@enduml