@startuml
' 隱藏圓點，避免與連結線衝突
hide circle
' 設定線條為正交直線
skinparam linetype ortho

' 繼承 django AbstractUse當作每個person
abstract class AbstractUser {
    + username
    + password
    + first_name
    + last_name
    + email
    + is_staff
    + is_active
    + is_superuser
    + last_login
    + date_joined
    + groups : manyToManyField
    + user_permissions : manyToManyField
}

class "User" as User {
    + username : {derived} {None}
    + email : {derived} {unique}
    ' + email : << override, unique=Ture >>
    --
    + full_name : String
    + date_of_birth : Date {optional}
    + avatar : Image {optional}
    + created_at : DateTime {auto_now_add=True}
    + updated_at : DateTime {auto_now=True}

    + phone : Str {optional} 'Could potentially use the  django-phonenumber-field package
    + is_verified : Bool {default=False}
}
AbstractUser <|-- User

' ------ 隊伍 ------
class "Team" as Team {
    + team_name : String {unique=True}
    + leader_id : <<FK>> {nullable}
    + coach_id : <<FK>> {nullable}
    + created_at : DateTime {auto_now_add=True}
    + updated_at : DateTime {auto_now=True}
    --
}

class "TeamMember" as TeamMember {
    + team_id : << FK >>
    + user_id : << FK >>
    --
    { unique_together = ('team_id', 'user_id')}
}

' ------ 比賽 ------
class "Event" as Event {
    + event_name : String
    + event_type : String 
    + location : String
    + start_time : DateTime
    + end_time : DateTime 'end_time > start_time
    + created_at : DateTime {auto_now_add=True}
    + updated_at : DateTime {auto_now=True}
}

' event_id, teamA_id, teamB_id 不為unique_together
' 避免複賽重複對戰
class "TeamMatch" as TeamMatch {
    + event_id : << FK >>
    + team_a_id : << FK >>
    + team_b_id : << FK >>
    --
    + team_a_score : Int {team_a_score >= 0}
    + team_b_score : Int {team_b_score >= 0}
    + match_date : DateField '紀錄對戰日期，支援跨日對戰
    + match_time : TimeField {nullable} '紀錄對戰時間，可以不填避免麻煩
    + match_status : Enum{Scheduled, InProgress, Completed}

    + created_at : DateTime
    + updated_at : DateTime
    --
}

class "PlayerMatch" as PlayerMatch {
    + team_match_id : << FK >>
    + match_format : Enum{Single, Double}
    + match_order : Int '第幾個排點
    + match_label : Str '點位名稱：男單 30混雙 50男雙....
    --
    + player_a_score : Int {player_a_score >= 0}
    + player_b_score : Int {player_b_score >= 0}
    + score_details : JsonField ' [{"a": "11", "b": "3"},
                                '  {"a": "11", "b": "3"},
                                '  {"a": "11", "b": "3"},]
    --
    + { unique_together = ('team_match_id', 'match_order')}
}

class "PlayerMatchParticipant" as PlayerMatchParticipant {
    + player_match_id : << FK >>
    + user_id : << FK >>
    + team_id : << FK >>
    --
    + position : Int {default=1} '在這裡表示打第幾號選手單打一號、雙打兩號以此累推
    --
    unique_together = (player_match_id, user_id)
}


' -------

User "1" -- "*" Team : leader
User "1" -- "*" Team : coach

User "1" -- "*" TeamMember
Team "1" -- "*" TeamMember

Event "1" -- "*" TeamMatch
Team "1" -- "*" TeamMatch : teamA
Team "1" -- "*" TeamMatch : teamB

TeamMatch "1" -- "*" PlayerMatch

PlayerMatch "1" -- "*" PlayerMatchParticipant
User "1" -- "*" PlayerMatchParticipant
Team "1" -- "*" PlayerMatchParticipant

@enduml