# Generated by Django 5.2.8 on 2025-12-17 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_user_core_user_email_index_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["id"]},
        ),
    ]
