# Generated by Django 5.2.8 on 2025-12-24 07:56

from django.db import migrations
from django.contrib.auth import get_user_model


def create_default_groups(apps, schema_editor):
    """
    Create the default authentication groups used by the application.
    
    Ensures the following groups exist in the auth Group model: "SuperAdmin", "EventManager", and "Member".
    
    Parameters:
        apps: The migration apps registry (used to retrieve the auth Group model).
        schema_editor: The database schema editor for this migration (not used).
    """
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name='SuperAdmin')
    Group.objects.get_or_create(name='EventManager')
    Group.objects.get_or_create(name='Member')

class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [migrations.RunPython(create_default_groups)]