# Generated by Django 6.0.1 on 2026-01-18 12:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_scocialaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='scocialaccount',
            name='social_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='scocialaccount',
            constraint=models.UniqueConstraint(fields=('social_id', 'social_type'), name='unique_social_type_social_id', violation_error_message='social_type and social_id may be unique'),
        ),
    ]
