# Generated by Django 6.0.1 on 2026-01-18 16:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_scocialaccount_social_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='scocialaccount',
            name='social_type',
            field=models.CharField(choices=[('google', 'Google'), ('facebook', 'Facebook'), ('apple', 'Apple')], max_length=8),
        ),
        migrations.AlterConstraint(
            model_name='scocialaccount',
            name='unique_social_type_social_id',
            constraint=models.UniqueConstraint(fields=('social_id', 'social_type'), name='unique_social_type_social_id', violation_error_message='A social account with this provider and ID already exist'),
        ),
    ]
