# Generated by Django 6.0.1 on 2026-07-17 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_usersetting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersetting',
            old_name='User',
            new_name='user',
        ),
    ]
