# Generated by Django 6.0.1 on 2026-07-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_user_usersetting_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersetting',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='language',
            field=models.CharField(blank=True, default='zh-Hant', max_length=32),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='sidebar_collapsed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='theme',
            field=models.CharField(blank=True, default='light', max_length=16),
        ),
    ]
