"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from dotenv import load_dotenv
from pathlib import Path
import datetime

load_dotenv()

def get_bool_env(key: str, default: str = 'False') -> bool:
    value = os.getenv(key, default=default).lower()
    return value in {'true', '1', 'yes', 'on', 't'}

DEBUG = get_bool_env('DEBUG')
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

ALLOW_HOST='PROD_ALLOW_HOST'

if DEBUG:
    ALLOW_HOST='ALLOW_HOST'


ALLOWED_HOSTS = [host.strip() for host in os.environ[ALLOW_HOST].split(',') if host.strip()]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'apps.core',
    'apps.users',
    'apps.teams',
    'apps.events',
    'apps.matches',
    'drf_spectacular',
    'django_extensions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware', ]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if os.getenv('CI'):
    SECRET_KEY = '(m)zk25=oele=qi*$==$l(x4loi%(x$pccsd&gj5v^m82514$c'
    
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": "test_db",
            "USER": "postgres",
            "PASSWORD": "postgres",
            "HOST": "localhost",
            "PORT": "5435",
        }
    }
else:
    SECRET_KEY = os.environ['NEXUS_SECRET_KEY']
    
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ['NEXUS_DB_NAME'],
            "USER": os.environ["NEXUS_DB_USER"],
            "PASSWORD": os.environ['NEXUS_DB_PWD'],
            "HOST": os.environ['NEXUS_DB_HOST'],
            "PORT": os.environ['NEXUS_DB_PORT'],
            'OPTIONS': {
                'pool': {
                    'min_size': 2,
                    'max_size': 4,
                },
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Taipei'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'core.User'

REST_FRAMEWORK = {
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.NamespaceVersioning',
    'DEFAULT_VERSION': 'v1',
    'ALLOWED_VERSIONS': ['v1',],

    'DEFAULT_AUTHENTICATION_CLASSES': (
        # 'rest_framework_simplejwt.authentication.JWTAuthentication',
        'apps.users.authentication.CustomJWTAuthentication',
        # 'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,

    'DEFAULT_THROTTLE_RATES': {
        'refresh': '10/minute',  # 限制refresh頻率，避免頻繁refresh造成DB壓力
    },
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Nexus Project API',
    'DESCRIPTION': '龍濱會員賽事系統',
    'VERSION': '0.0.1',
    'SERVE_INCLUDE_SCHEMA': False,

    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,
        "persistAuthorization": True,
        "displayOperationId": True,
    },
    'COMPONENT_SPLIT_REQUEST': True,

    
    'SECURITY': [{'jwt_auth': []}],
    'APPEND_COMPONENTS': {
        'securitySchemes': {
            'jwt_auth': {
                'type': 'oauth2',
                'description': '輸入帳密登入取得 Token',
                'flows': {
                    'password': {
                        'tokenUrl': '/api/v1/users/login/',
                        'scopes': {},
                    }
                }
            }
        }
    }
}

SIMPLE_JWT = {
    'TOKEN_REFRESH_SERIALIZER': 'apps.users.serializers.MyToeknRefreshSerializer',
    'TOKEN_OBTAIN_SERIALIZER': 'apps.users.serializers.MyTokenObtainPairSerializer',
    'ACCESS_TOKEN_LIFETIME': datetime.timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': datetime.timedelta(hours=2),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

# Celery
CELERY_TIMEZONE = 'Asia/Taipei'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60
CELERY_BROKER_URL = f'redis://:{os.environ["REDIS_PASSWORD"]}@localhost:6379/2'
CELERY_RESULT_BACKEND = f'redis://:{os.environ["REDIS_PASSWORD"]}@localhost:6379/3'
CELERY_RESULT_EXPIRES = 60*60

# Mailtrap
MAILTRAP_USE_SANDBOX = False
MAILTRAP_API_KEY = os.getenv('MAILTRAP_KEY')
MAILTRAP_DOMAIN = os.getenv('MAILTRAP_DOMAIN')
MAILTRAP_INBOX_ID = os.getenv('MAILTRAP_INBOX_ID')
if DEBUG:
    MAILTRAP_USE_SANDBOX = True

SITE_BASEURL = 'localhost:8000'

GOOGLE_WEB_CLIENT_ID = os.getenv('GOOGLE_OAUTH_CLIENT_ID')
GOOGLE_OAUTH_SECRET_FILE_PATH = os.getenv('GOOGLE_OAUTH_SCRECT_FILE_PATH')

if os.getenv('CI'):
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": os.environ['REDIS_LOCATION'],
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
                "PASSWORD": os.environ['REDIS_PASSWORD'],
            }
        }
    }

ROLE_ACTIONS_MAP = {
    'SuperAdmin': {
        'member:list', 'member:create', 'member:destroy',
        'event:list', 'event:create', 'event:destroy',
        'own_data:retrieve', 'own_data:edit'
    },
    'EventManager':{
        'member:list', 'member:create', 'member:destroy',
        'event:list', 'event:create', 'event:destroy',
        'own_data:retrieve', 'own_data:edit'
    },
    'Member':{
        'event:list',
        'own_data:retrieve', 'own_data:edit'
    },
}

LOGGING = {
    "version": 1,  # the dictConfig format version
    "disable_existing_loggers": False,  # retain the default loggers
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': 'logs/django_app.log',
            'maxBytes': 1024 * 1024 * 5,
            'backupCount': 5,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
    },
    'loggers': {
        '': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
        },
        'django': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}


