"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from dotenv import dotenv_values, load_dotenv
from pathlib import Path
import datetime

BASE_DIR = Path(__file__).resolve().parent.parent

def _is_production() -> bool:
    has_secret_file = Path('/run/secrets/.env.prod').exists()
    debug_val = os.getenv('DEBUG', 'False' if has_secret_file else 'True').lower()
    return debug_val not in {'true', '1', 'yes', 'on', 't'}

IS_PRODUCTION: bool = _is_production()
DEBUG: bool = not IS_PRODUCTION

APP_CONFIG: dict[str, str] = {}

if IS_PRODUCTION:
    for config_path in [Path('/run/secrets/.env.prod'), BASE_DIR / '.env.prod']:
        if config_path.exists():
            APP_CONFIG = {k: v for k, v in dotenv_values(config_path).items() if v is not None}
            break
else:
    load_dotenv(BASE_DIR / '.env')


def get_conf(key: str) -> str:
    if IS_PRODUCTION:
        val = APP_CONFIG.get(key)
        if not val:
            raise KeyError(f"Required configuration '{key}' not found in production configuration file (.env.prod)!")
        return val
    val = os.environ.get(key)
    if not val:
        raise KeyError(f"Required configuration '{key}' not found in environment (.env)!")
    return val


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

ALLOW_HOST = 'ALLOW_HOST' if DEBUG else 'PROD_ALLOW_HOST'
_hosts_val = get_conf(ALLOW_HOST)
ALLOWED_HOSTS = [host.strip() for host in _hosts_val.split(',') if host.strip()]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_prometheus',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'apps.core',
    'apps.users',
    'apps.teams',
    'apps.events',
    'apps.matches',
    'apps.notification',
    'drf_spectacular',
    'django_extensions',
]

MIDDLEWARE = [
    'django_prometheus.middleware.PrometheusBeforeMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'djangorestframework_camel_case.middleware.CamelCaseMiddleWare',
    'django_prometheus.middleware.PrometheusAfterMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if os.getenv('CI'):
    SECRET_KEY = '(m)zk25=oele=qi*$==$l(x4loi%(x$pccsd&gj5v^m82514$c'
    
    DATABASES = {
        "default": {
            "ENGINE": "django_prometheus.db.backends.postgresql",
            "NAME": "test_db",
            "USER": "postgres",
            "PASSWORD": "postgres",
            "HOST": "localhost",
            "PORT": "5435",
        }
    }
else:
    SECRET_KEY = get_conf('NEXUS_SECRET_KEY')

    DATABASES = {
        "default": {
            "ENGINE": "django_prometheus.db.backends.postgresql",
            "NAME": get_conf('NEXUS_DB_NAME'),
            "USER": get_conf("NEXUS_DB_USER"),
            "PASSWORD": get_conf('NEXUS_DB_PWD'),
            "HOST": get_conf('NEXUS_DB_HOST'),
            "PORT": get_conf('NEXUS_DB_PORT'),
            'OPTIONS': {
                'pool': {
                    'min_size': 2,
                    'max_size': 4,
                },
            },
        }
    }



STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "endpoint_url": get_conf("R2_API"),
            "access_key": get_conf("R2_ACCESS_KEY"),
            "secret_key": get_conf("R2_SECRET_KEY"),
            "bucket_name": get_conf("R2_BUCKET_NAME"),
            "region_name": "auto",

            "querystring_auth": True,
            "querystring_expire": 3600,
            "default_acl": None,

            "file_overwrite": False,

            "location": "static",
            "querystring_auth": True,

        },
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Taipei'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'core.User'

REST_FRAMEWORK = {
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.NamespaceVersioning',
    'DEFAULT_VERSION': 'v1',
    'ALLOWED_VERSIONS': ['v1',],

    'DEFAULT_AUTHENTICATION_CLASSES': (
        # 'rest_framework_simplejwt.authentication.JWTAuthentication',
        'apps.users.authentication.CustomJWTAuthentication',
        # 'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,

    'DEFAULT_THROTTLE_RATES': {
        'refresh': '10/minute',  # 限制refresh頻率，避免頻繁refresh造成DB壓力
    },
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',

    'DEFAULT_RENDERER_CLASSES': (
        'djangorestframework_camel_case.render.CamelCaseJSONRenderer',
        'djangorestframework_camel_case.render.CamelCaseBrowsableAPIRenderer',
    ),

    'DEFAULT_PARSER_CLASSES': (
        # If you use MultiPartFormParser or FormParser, we also have a camel case version
        'djangorestframework_camel_case.parser.CamelCaseFormParser',
        'djangorestframework_camel_case.parser.CamelCaseMultiPartParser',
        'djangorestframework_camel_case.parser.CamelCaseJSONParser',
    ),
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Nexus Project API',
    'DESCRIPTION': '會員賽事系統',
    'VERSION': '0.0.1',
    'SERVE_INCLUDE_SCHEMA': False,

    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,
        "persistAuthorization": True,
        "displayOperationId": True,
    },
    'COMPONENT_SPLIT_REQUEST': True,

    
    'SECURITY': [{'jwt_auth': []}],
    'APPEND_COMPONENTS': {
        'securitySchemes': {
            'jwt_auth': {
                'type': 'oauth2',
                'description': '輸入帳密登入取得 Token',
                'flows': {
                    'password': {
                        'tokenUrl': '/api/v1/users/login/',
                        'scopes': {},
                    }
                }
            }
        }
    },
    'ENUM_NAME_OVERRIDES': {
        'EventTeamStatusEnum': 'apps.events.models.EventTeam.StatusChoices',
        'MatchStatusEnum': 'apps.matches.models.BaseMatch.StatusChoices',
    },
}

SIMPLE_JWT = {
    'TOKEN_REFRESH_SERIALIZER': 'apps.users.serializers.MyToeknRefreshSerializer',
    'TOKEN_OBTAIN_SERIALIZER': 'apps.users.serializers.MyTokenObtainPairSerializer',
    'ACCESS_TOKEN_LIFETIME': datetime.timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': datetime.timedelta(hours=2),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

# Celery
CELERY_TIMEZONE = 'Asia/Taipei'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60

_redis_pwd = get_conf('REDIS_PASSWORD')
_redis_host = get_conf('REDIS_HOST')
_redis_port = get_conf('REDIS_PORT')
_redis_db = get_conf('REDIS_DB')

CELERY_BROKER_URL = f'redis://:{_redis_pwd}@{_redis_host}:{_redis_port}/2'
CELERY_RESULT_BACKEND = f'redis://:{_redis_pwd}@{_redis_host}:{_redis_port}/3'
CELERY_RESULT_EXPIRES = 60 * 60

# Mailtrap
MAILTRAP_USE_SANDBOX = False
MAILTRAP_API_KEY = get_conf('MAILTRAP_KEY')
MAILTRAP_DOMAIN = get_conf('MAILTRAP_DOMAIN')
MAILTRAP_INBOX_ID = get_conf('MAILTRAP_INBOX_ID')
if DEBUG:
    MAILTRAP_USE_SANDBOX = True

SITE_BASEURL = 'localhost:8000'

GOOGLE_WEB_CLIENT_ID = get_conf('GOOGLE_OAUTH_CLIENT_ID')
if IS_PRODUCTION:
    GOOGLE_CLIENT_SECRET_JSON = get_conf('GOOGLE_CLIENT_SECRET_JSON')
    GOOGLE_OAUTH_SECRET_FILE_PATH = None
else:
    GOOGLE_CLIENT_SECRET_JSON = os.environ.get('GOOGLE_CLIENT_SECRET_JSON', '')
    GOOGLE_OAUTH_SECRET_FILE_PATH = os.environ.get('GOOGLE_OAUTH_SCRECT_FILE_PATH', '')

if DEBUG:
    TEMPLATES[0]['DIRS'] += [BASE_DIR / "frontend" / "dist" / "test-google-login"]

    if 'STATICFILES_DIRS' not in locals():
        STATICFILES_DIRS = []
    STATICFILES_DIRS += [BASE_DIR / "frontend" / "dist" / "test-google-login"]

if os.getenv('CI'):
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": f'redis://{_redis_host}:{_redis_port}/{_redis_db}',
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
                "PASSWORD": _redis_pwd,
            }
        }
    }

ROLE_ACTIONS_MAP = {
    'SuperAdmin': {
        'member:list', 'member:create', 'member:destroy',
        'event:list', 'event:create', 'event:destroy',
        'own_data:retrieve', 'own_data:edit'
    },
    'EventManager':{
        'member:list', 'member:create', 'member:destroy',
        'event:list', 'event:create', 'event:destroy',
        'own_data:retrieve', 'own_data:edit'
    },
    'Member':{
        'event:list',
        'own_data:retrieve', 'own_data:edit'
    },
}

LOGGING = {
    "version": 1,  # the dictConfig format version
    "disable_existing_loggers": False,  # retain the default loggers
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': 'logs/django_app.log',
            'maxBytes': 1024 * 1024 * 5,
            'backupCount': 5,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
    },
    'loggers': {
        '': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
        },
        'django': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# Django Prometheus Settings
# Define latency buckets (in seconds) to enable p95/p99 histograms for DB queries
PROMETHEUS_LATENCY_BUCKETS = (.008, .016, .032, .064, .128, .256, .512, 1.024, 2.048, 4.096, 8.192, 16.384, 32.768, 65.536, 131.072, 262.144, 524.288, 1048.576)
PROMETHEUS_EXPORT_MIGRATIONS = False


