# Generated by Django 6.0.1 on 2026-08-03 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=32)),
                ('body', models.CharField(blank=True, default='', max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('WEB', 'WEB')], default='WEB', max_length=3)),
                ('notification_type', models.CharField(choices=[('SA', 'SYSTEM_ALERT'), ('SB', 'STATUS_BAR')], default='SB', max_length=2)),
                ('status', models.CharField(choices=[('UR', 'unread'), ('R', 'read'), ('D', 'deleted')], default='UR', max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_type', models.CharField(blank=True, default='', max_length=32)),
                ('target_id', models.CharField(blank=True, default='', max_length=36)),
                ('target_key', models.CharField(blank=True, default='', max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notification_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'target_type', 'target_id', 'target_key'), name='notification_notificationlog_unique_user_targetType_targetID', violation_error_message='The combination of user/target_typeand target_id must be unique')],
            },
        ),
    ]
