# Generated by Django 6.0.1 on 2026-08-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_rename_notification_type_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='body',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('SA', 'SYSTEM_ALERT'), ('SI', 'SYSTEM_INFO'), ('SW', 'SYSTEM_WARNING'), ('SB', 'STATUS_BAR')], default='SI', max_length=2),
        ),
    ]
