apiVersion: 1

datasources:
  - name: Prometheus-Prod
    type: prometheus
    uid: DS_PROMETHEUS
    access: proxy
    url: http://prometheus_prod:9090
    isDefault: ${GF_IS_DEFAULT_PROD}
    editable: false
