# Generated by Django 6.0.1 on 2026-02-03 04:36

import django.db.models.deletion
import django.db.models.functions.comparison
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0009_eventmatchtemplateitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('number', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('SC', 'Scheduled'), ('IP', 'In Progress'), ('CP', 'Completed'), ('XX', 'Cancelled')], default='SC', max_length=2)),
                ('winner', models.CharField(blank=True, choices=[('A', 'Team_A'), ('B', 'Team_B'), ('D', 'Draw')], max_length=1)),
                ('team_a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_matches_a', to='events.eventteam')),
                ('team_b', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_matches_b', to='events.eventteam')),
            ],
            options={
                'ordering': ['number'],
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='PlayerMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('format', models.CharField(choices=[('S', 'Single'), ('D', 'Double')], default='S', max_length=1, verbose_name='match format')),
                ('requirement', models.CharField(blank=True, default='', help_text='Specify the age, gender, or category for this match (e.g., "30+ Men\'s Singles", "120+ Mixed Doubles").', max_length=32, verbose_name='Match requirement')),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('number', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('SC', 'Scheduled'), ('IP', 'In Progress'), ('CP', 'Completed'), ('XX', 'Cancelled')], default='SC', max_length=2)),
                ('winner', models.CharField(blank=True, choices=[('A', 'Team_A'), ('B', 'Team_B'), ('D', 'Draw')], max_length=1)),
                ('team_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_matches', to='matches.teammatch')),
            ],
            options={
                'ordering': ['number'],
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='MatchSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('set_number', models.IntegerField(default=0, verbose_name='set number')),
                ('score_a', models.IntegerField(default=0, verbose_name='team A score')),
                ('score_b', models.IntegerField(default=0, verbose_name='team B score')),
                ('player_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='matches.playermatch')),
            ],
            options={
                'ordering': ['set_number'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('player_match', 'set_number'), name='matches_matchset_unique_match_set_order', violation_error_message='This set number already exists for this match')],
            },
        ),
        migrations.CreateModel(
            name='PlayerMatchParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player_name_backup', models.CharField(blank=True, default='', max_length=128)),
                ('side', models.CharField(choices=[('A', 'Team A'), ('B', 'Team B')], default='A', max_length=1, verbose_name='Side')),
                ('position', models.IntegerField(default=1, verbose_name='Position')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_participations', to=settings.AUTH_USER_MODEL)),
                ('player_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='matches.playermatch')),
            ],
            options={
                'ordering': ['side', 'position'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('player_match', 'player'), name='matches_playermatchparticipant_unique_participant', violation_error_message='This player already exists for this match'), models.UniqueConstraint(fields=('player_match', 'side', 'position'), name='matches_playermatchparticipant_unique_side_position', violation_error_message='This position on this side is already occupied.'), models.CheckConstraint(condition=models.Q(('position__in', [1, 2])), name='matches_playermatchparticipant_check_position_1_or_2', violation_error_message='Position must be 1 or 2')],
            },
        ),
        migrations.AddConstraint(
            model_name='teammatch',
            constraint=models.CheckConstraint(condition=models.Q(('team_a', models.F('team_b')), _negated=True), name='matches_teammatch_check_team_a_ne_team_b', violation_error_message='Team A and Team B must be different.'),
        ),
        migrations.AddConstraint(
            model_name='teammatch',
            constraint=models.UniqueConstraint(django.db.models.functions.comparison.Least('team_a', 'team_b'), django.db.models.functions.comparison.Greatest('team_a', 'team_b'), name='matches_teammatch_unique_matchup', violation_error_message='This team matchup already exists in the system.'),
        ),
        migrations.AddConstraint(
            model_name='playermatch',
            constraint=models.UniqueConstraint(fields=('team_match', 'number'), name='matches_playermatch_unique_match_order', violation_error_message='This match number is already assigned in this team match.'),
        ),
    ]
