# Generated by Django 5.2.8 on 2025-12-26 10:56

import django.db.models.functions.comparison
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_lunchoption_registrationlunchorder"),
        ("matches", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="playermatchparticipant",
            options={"ordering": ["side", "position"]},
        ),
        migrations.RemoveConstraint(
            model_name="teammatch",
            name="matches_teammatch_unique_number",
        ),
        migrations.AddField(
            model_name="playermatchparticipant",
            name="side",
            field=models.CharField(
                choices=[("A", "Team A"), ("B", "Team B")],
                default="A",
                max_length=1,
                verbose_name="Side",
            ),
        ),
        migrations.AddConstraint(
            model_name="playermatchparticipant",
            constraint=models.UniqueConstraint(
                fields=("player_match", "side", "position"),
                name="matches_playermatchparticipant_unique_side_position",
                violation_error_message="This position on this side is already occupied.",
            ),
        ),
        migrations.AddConstraint(
            model_name="playermatchparticipant",
            constraint=models.CheckConstraint(
                condition=models.Q(("position__in", [1, 2])),
                name="matches_playermatchparticipant_check_position_1_or_2",
                violation_error_message="Position must be 1 or 2",
            ),
        ),
        migrations.AddConstraint(
            model_name="teammatch",
            constraint=models.UniqueConstraint(
                django.db.models.functions.comparison.Least("team_a", "team_b"),
                django.db.models.functions.comparison.Greatest("team_a", "team_b"),
                name="matches_teammatch_unique_matchup",
                violation_error_message="This team matchup already exists in the system.",
            ),
        ),
    ]
