# Generated by Django 5.2.8 on 2026-01-08 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_alter_playermatchparticipant_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchtemplate',
            options={'ordering': ['-created_at']},
        ),
    ]
