# Generated by Django 6.0.1 on 2026-01-28 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_alter_matchtemplate_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmatchconfiguration',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventmatchconfiguration',
            name='template',
        ),
        migrations.RemoveField(
            model_name='matchtemplate',
            name='creator',
        ),
        migrations.RemoveConstraint(
            model_name='matchtemplateitem',
            name='matches_matchtemplateitem_unique_template_item_number',
        ),
        migrations.DeleteModel(
            name='EventMatchConfiguration',
        ),
        migrations.RemoveField(
            model_name='matchtemplateitem',
            name='template',
        ),
        migrations.DeleteModel(
            name='MatchTemplate',
        ),
        migrations.DeleteModel(
            name='MatchTemplateItem',
        ),
    ]